### ISSUE TITLE
imposm: TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by frafra** [kartoza/docker-osm#125]
```
dockerosm-imposm-1     | Mapping: settings/mapping.yml
dockerosm-imposm-1     | Load Mapping file data.
dockerosm-imposm-1     | Traceback (most recent call last):
dockerosm-imposm-1     |   File "/home/enrich.py", line 622, in <module>
dockerosm-imposm-1     |     enrich = Enrich()
dockerosm-imposm-1     |   File "/home/enrich.py", line 78, in __init__
dockerosm-imposm-1     |     self.check_settings()
dockerosm-imposm-1     |   File "/home/enrich.py", line 102, in check_settings
dockerosm-imposm-1     |     self.check_mapping_file_data()
dockerosm-imposm-1     |   File "/home/enrich.py", line 177, in check_mapping_file_data
dockerosm-imposm-1     |     mapping_data = yaml.load(document)
dockerosm-imposm-1     | TypeError: load() missing 1 required positional argument: 'Loader'
```

**Comment by frafra** [comment]
This is because of https://github.com/yaml/pyyaml/commit/0cedb2a0697b2bc49e4f3841b8d4590b6b15657e.
