### ISSUE TITLE
enrich.py: string indices must be integers

### ISSUE THREAD

**Issue by frafra** [kartoza/docker-osm#130]
osmenrich fails:
```
dockerosm-osmenrich-1  | Error when processing 2022-09-20T16:58:07Z->-2022-09-20T17:00:09Z.osc.gz : string indices must be integers
```

Removing the wide and generic try/except here shows some details:

https://github.com/kartoza/docker-osm/blob/f3452495f9ddeb71f40662d3447e71ba4dcf5120/docker-osmenrich/enrich.py#L581-L582

```
dockerosm-osmenrich-1  | Traceback (most recent call last):
dockerosm-osmenrich-1  |   File "/home/enrich.py", line 618, in <module>
dockerosm-osmenrich-1  |     enrich.run()
dockerosm-osmenrich-1  |   File "/home/enrich.py", line 609, in run
dockerosm-osmenrich-1  |     self.enrich_database_from_diff_file()
dockerosm-osmenrich-1  |   File "/home/enrich.py", line 566, in enrich_database_from_diff_file
dockerosm-osmenrich-1  |     self.enrich_database_from_osm_data(
dockerosm-osmenrich-1  |   File "/home/enrich.py", line 508, in enrich_database_from_osm_data
dockerosm-osmenrich-1  |     osm_id = self.check_data_on_dict(
dockerosm-osmenrich-1  |   File "/home/enrich.py", line 301, in check_data_on_dict
dockerosm-osmenrich-1  |     return data[key]
dockerosm-osmenrich-1  | TypeError: string indices must be integers
dockerosm-osmenrich-1 exited with code 1
```

It looks that `data` can just be a string, such as `@id`.

**Comment by frafra** [comment]
Fixed by a different commit.
